apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-gzctf-deployer
  namespace: gzctf-server
  labels:
    app.kubernetes.io/name: gzctf
    app.kubernetes.io/component: deployer
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-gzctf-deployer-token
  namespace: gzctf-server
  labels:
    app.kubernetes.io/name: gzctf
    app.kubernetes.io/component: deployer
  annotations:
    kubernetes.io/service-account.name: gitea-gzctf-deployer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-gzctf-deployer
  namespace: gzctf-server
  labels:
    app.kubernetes.io/name: gzctf
    app.kubernetes.io/component: deployer
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["gzctf"]
    verbs: ["get", "patch", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-gzctf-deployer
  namespace: gzctf-server
  labels:
    app.kubernetes.io/name: gzctf
    app.kubernetes.io/component: deployer
subjects:
  - kind: ServiceAccount
    name: gitea-gzctf-deployer
    namespace: gzctf-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitea-gzctf-deployer
